language: ruby
rvm:
  - 2.0.0
notifications:
  email: true
branches:
  only:
    - master
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - phantomjs --version
  - psql -c 'create database furioustypist_test;' -U postgres
  - rake db:migrate
  - rake db:test:prepare
  - rake db:seed
  - rake sunspot:reset_without_reindex
