common: &common
  adapter: postgresql
  encoding: utf8
  pool: 5
  min_messages: WARNING
  host: localhost

development:
  <<: *common
  database: furioustypist_dev

test: &test
  <<: *common
  database: furioustypist_test

production:
  <<: *common
  database: furioustypist_prod

cucumber:
  <<: *test
